### ISSUE TITLE
Desert island discussion

### ISSUE THREAD

**Issue by Zylleon** [biomes-team/BiomesIslands#11]
Desert island planning.
**Overview:** Barren, stranded, sunbaked. Inverted oasis. Should have the highest sea:land life ratio. Sort of like the galapagos islands. Reasonably barren feeling but not unsurvivable. You use the seas or you likely starve.

The land should be mostly empty, with just a few small creatures and hardy plants. The sea should be lively and colorful, coral-reef-like

**Water animals, predators**

- Spotted Stingray - Medium sized predator, eats fish and crabs most. Skin is decent quality. 
- White-tip Reef Shark - smaller shark predator, decent skin. Largely not dangerous to humans unless manhunter. 
- Black-tip Reef Shark - Much the same as above
- Hammerhead Shark - Same as other islands
- Moray Eel - Striped eel predator, ambush predator somehow?

**Water animals, prey**

- Manta Rays - Gentle giants, prey to sharks. Worth a lot of money?
- Sunfish - Large and good for meat, not dangerous, 
- Green sea turtle - Same as other islands
- Medium tropical fish: Mega Moorish idol
- Small tropical fish: pufferfish
- Small tropical fish: surgeonfish
- Small tropical fish: clownfish

**Water plants**
A few water plants or corals? Possibly something edible, like a fruiting seaweed?

**Land animals**

- Marine Iguana - (Desert island exclusive)
- Galapagos tortoise - Medium sized, herbivore, No predators, Shell is worth a lot?. They're a slow moving tortoise that is no threat but half decent source of meat if you wanna be a monster. Sleep a lot throughout the day. 
- Salty Lightfood crab - Small omnivore like other crabs, quite colorful. Easy meat
Komodo Dragon - Large predator, bite has an extremely high chance of causing infection.

**Land plants**

- Prickly Pair Cactus - Highly common, edible for animals.  

**Other**

**Comment by MSeal** [comment]
Can we copy notes from the discord channel here? I have trouble scrolling through them to find the conclusions. @Zylleon @draegon1993

**Comment by draegon1993** [comment]
@MSeal We will once we have Desert Islands planned out, we have not decided on what to have in them yet
