### ISSUE TITLE
Sea Life missing attacks

### ISSUE THREAD

**Issue by draegon1993** [biomes-team/BiomesIslands#28]
Sea life need to be reviewed to ensure they each have at least one type of attack. 
This should include a headbutt attack, to ensure that all living fish have at least one attack even if missing some body parts.

XML files to check:

- [x] BiomesIslands_Races_Aquatic
- [x] BiomesIslands_Races_Baitfish
- [x] BiomesIslands_Races_Whales

**Comment by Zylleon** [comment]
Added a headbutt attack to all sea life that was missing it
